#!/bin/sh

# Abaixa o som, que la vem pedrada
# USE ONLY in Non-systemd systems

true "${XDG_CONFIG_HOME:=${HOME}/.config}"

pkill -TERM wireplumber
pkill -TERM pipewire
pkill -TERM xdg-desktop-por

pgrep -x pipewire || (pipewire &)

pgrep xdg-desktop-por || {
	pgrep -x wireplumber || exec $0

	/usr/libexec/xdg-desktop-portal &
	/usr/libexec/xdg-desktop-portal-gtk &
	/usr/libexec/xdg-desktop-portal-wlr &
}
