#!/bin/bash
set -eu

#> dep: gnome-settings-daemon
#> dep: river

cursor_theme=capitaine-cursors
cursor_size=16
gtk_theme=adw-gtk3-dark
icon_theme=Papirus-Dark
font_name="IBM Plex Sans 10"
monofont_name="Roboto Mono 11"
gnome_schema="org.gnome.desktop.interface"

pgrep -x gsd-xsettings || /usr/lib/gsd-xsettings &

gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" cursor-size "$cursor_size"
gsettings set "$gnome_schema" font-name "$font_name"
gsettings set "$gnome_schema" monospace-font-name "$monofont_name"
riverctl xcursor-theme $cursor_theme $cursor_size

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x957FB8
riverctl border-color-unfocused 0x1F1F28
riverctl border-width 1

echo "#!/bin/bash
exec env XCURSOR_THEME=\"${cursor_theme}\" XCURSOR_SIZE=${cursor_size} river" >~/.config/river/start
