#!/usr/bin/env bash
set -euo pipefail

bye() {
	kill $(jobs -p)
}

systemctl --user restart mako || echo "WARNING: Mako not found."
pgrep -x eww                  || eww -c ~/.config/hypr/cfg/eww open main 

~/.config/hypr/bin/hyprtheme
trap bye EXIT
wait
